### ISSUE TITLE
Trying to use it with next.js get error

### ISSUE THREAD

**Issue by nikivdev** [GriffinJohnston/ldrs#1]
I only imported it with `import { Ring } from "@uiball/loaders"` and then tried to use it. I get this error though:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/6391776/164006421-83d07df6-4017-47db-ade9-4856d7ef740c.png">

Any idea what might cause it?

**Comment by GriffinJohnston** [comment]
Hi Nikita - this is happening because loaders are exported with ESM syntax to allow for tree-shaking, and Next doesn't transpile imported modules by default. Try https://www.npmjs.com/package/next-transpile-modules. There's more detail here as well: https://stackoverflow.com/a/65939797

Let me know if that works for you!

**Comment by nikivdev** [comment]
That worked, thank you ♥️

**Comment by GriffinJohnston** [comment]
Glad to hear it! I should probably put a note in the docs. Thanks for bringing that up!

**Comment by nikivdev** [comment]
It would also be great if you can add TS types to the package if you get time. I have to `// @ts-ignore` the import. Not critical but would be nice. 😺

**Comment by GriffinJohnston** [comment]
Ah yea of course. I'll absolutely add types. I hate having to `// ignore` things

**Comment by GriffinJohnston** [comment]
@nikitavoloboev Types added with v1.2.3

**Comment by GriffinJohnston** [comment]
@nikitavoloboev With v1.2.6 using `next-transpile-modules` should no longer be necessary as long as you're using Next 12+ — give it a try if you don't mind, and let me know if it's working for you!

**Comment by nikivdev** [comment]
Amazing, thanks a lot for adding it!

**Comment by nikivdev** [comment]
Just tested it without transpile and it worked. 🎊
