### ISSUE TITLE
Error when installing UI Ball

### ISSUE THREAD

**Issue by grsx-1968** [GriffinJohnston/ldrs#12]
Hey there! I was interested in trying ui Ball loaders for my computer, I installed npm and ran  
npm i @uiball/loaders. 
After choosing the loader I wanted I went ahead and placed the proper code for it in the terminal, however, that's where the problem was. After pressing enter it gave me 
zsh: parse error near `}'
which is not letting me continue on with the process. 
Is there anything done wrong with the coding? 
Thanks in advance!

**Comment by GriffinJohnston** [comment]
Hi, did you paste the loader code directly into your terminal? That won't do anything. This project is a set of React components, so you need to use them in the context of a React app.

**Comment by grsx-1968** [comment]
I see, and how would I do that?

**Comment by GriffinJohnston** [comment]
React is primarily used to build web interfaces. You can learn more here: https://react.dev/
