### ISSUE TITLE
Is there any solution to testing?

### ISSUE THREAD

**Issue by gabrielcaamargo** [GriffinJohnston/ldrs#13]
I am using Jest to test my React application and I'm getting this error on @uiball library. I have already set a lot of configuration lines and nothing works. 

![image](https://github.com/GriffinJohnston/uiball-loaders/assets/91189919/39473bb9-4c2b-409f-b95a-727ac671907d)

**Comment by GriffinJohnston** [comment]
This package is pure ESM, meaning that a CommonJS export isn't available. You can learn about using ESM in the Jest docs: https://jestjs.io/docs/ecmascript-modules
