### ISSUE TITLE
Loader is not showing up 

### ISSUE THREAD

**Issue by serkan-bayram** [GriffinJohnston/ldrs#14]
I'm using NextJS and tried to use a loader as importing a React component but it is not showing up, anything else (like a div) is working without problem, I also tried to use HTML, CSS version of loader and it showed up but it was in a weird blue square. Do you have an idea?

**Comment by GriffinJohnston** [comment]
Which loader? Do you have a link to a reproduction of the problem? Any error messages?

**Comment by serkan-bayram** [comment]
Okay, it turns out I needed to put Loader inside a client component, it works fine now. I didn't see anything like that on the documentation, if it's not written it would be great if you can write it somewhere :)
