### ISSUE TITLE
npm readme 

### ISSUE THREAD

**Issue by AmrTamer23** [GriffinJohnston/ldrs#15]
First of all thank you for the amazing package, it's a very smooth experience to me so far.

But a small thing can make the experience smoother in my opinion is to add a readme in npm with minimal examples for the frameworks.

If I can help with this please let me know.

**Comment by GriffinJohnston** [comment]
There is a readme! https://www.npmjs.com/package/ldrs#ldrs

**Comment by AmrTamer23** [comment]
Ok got it but some how it looked like this before, anyway thx. 
![Screenshot from 2023-11-07 19-59-17](https://github.com/GriffinJohnston/ldrs/assets/122938074/30c249af-bf7b-470d-a44d-e68e673e9f3c)

**Comment by GriffinJohnston** [comment]
Strange, NPM being broken I guess!
