### ISSUE TITLE
Randomly occurring "Failed to execute 'insertBefore' on 'Node' error in React app"

### ISSUE THREAD

**Issue by matascirba1** [GriffinJohnston/ldrs#17]
Noticed an error in our applications logs after I started using <l-ring> loader inside CRA react application.

```
"Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.","cause":"React ErrorBoundary Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."
```

Going through stack trace it leads to our loader component which in turn renders **l-ring** component.

Loader currently is being mounted and unmounted on loading state changes. It seems that hiding loader with ```display: none;``` prevents this issue, but it would be nice to be able safely unmount component without crash.

Last time I encountered similar issue was caused by Stencil slot polyfill functionality for web-components with shadow DOM turned off where slotted children would be placed dynamically outside reacts parent component. 

Maybe something similar is happening here?

versions used: 
    "ldrs": "^1.0.1",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",

**Comment by GriffinJohnston** [comment]
Hi, thanks for the details. This is a new one! I'll do some investigating when I have a moment.

**Comment by GriffinJohnston** [comment]
Okay, a couple things:

1. It would be great if you could provide a little more context. A codesandbox or something similar with a recreation of the issue would be best. But even just a code snippet that shows how you're using the loader would be helpful.
2. Based on the error it looks like you're including the loader inside a container with other child nodes. ie:

```
<div>
    <l-ring></l-ring>
    Some text.
</div>
```

Try wrapping the loader in a `span` or `div` with no sibling elements or text:

```
<div>
    <span><l-ring></l-ring></span>
    Some text.
</div>
```

Let me know if that fixes the issue. I believe this may be a similar problem to [#11538](https://github.com/facebook/react/issues/11538)

**Comment by GriffinJohnston** [comment]
Unable to reproduce.
