### ISSUE TITLE
Cant remove LDR from site

### ISSUE THREAD

**Issue by joebynight** [GriffinJohnston/ldrs#18]
I embedded a LDR on a square space website, embedded using the code embed feature on an actual page of the site. the LDR shows up when the page is loading on the top left corner (see image), and I deleted the embed off of the page to start again but the LDR won't disappear and I cant find the code for it anywhere. 
![Screenshot 2023-11-29 at 8 54 42 AM](https://github.com/GriffinJohnston/ldrs/assets/152424368/138dd934-87f7-4a7f-bf9b-63d74a583019)

**Comment by GriffinJohnston** [comment]
This is a Squarespace issue, not a problem with this library. I suggest reaching out to their support!
