### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by ugursepetci** [GriffinJohnston/ldrs#2]
Will you provide typescript support?

**Comment by GriffinJohnston** [comment]
Yes! Working on it.

**Comment by mak-irwin** [comment]
looking forward to it 💪

**Comment by GriffinJohnston** [comment]
@ugursepetci @irwinmck Typing added with v1.2.2 — I've tested it and it should be working fine, but I'm not much of a TS user, so let me know if there are any issues with how I've implemented!

**Comment by ugursepetci** [comment]
@GriffinJohnston thank you! Types should not be required as they are default values. I sent a pr for this.

**Comment by GriffinJohnston** [comment]
@ugursepetci Good catch and thanks for the PR! Merged. #3
