### ISSUE TITLE
Nextjs Usage Issue  [ Property 'l-helix' does not exist on type 'JSX.IntrinsicElements' ] 

### ISSUE THREAD

**Issue by dawit-michael** [GriffinJohnston/ldrs#20]
`import "ldrs/helix";
export function LoadingSpinner() {
  return (
    <>
      <l-helix size="30" speed="1.75" color="black"></l-helix>
    </>
  );
}
`
![image](https://github.com/GriffinJohnston/ldrs/assets/32758991/f3bba126-9a77-41f0-9365-83b9865b1841)

I'm using 
**nextjs 14.0.3
ldrs 1.0.1**

**Comment by GriffinJohnston** [comment]
Next has some specific gotchas. Have you read through the NextJS platform guide?https://github.com/GriffinJohnston/ldrs/blob/main/framework-guides.md#nextjs

**Comment by dawit-michael** [comment]
> Next has some specific gotchas. Have you read through the NextJS platform guide?https://github.com/GriffinJohnston/ldrs/blob/main/framework-guides.md#nextjs

Having checked the guide. I've used the dynamic import and its working perfectly, Thank you.
