### ISSUE TITLE
Usage with React suspense boundaries (Next.js app router loading pages)

### ISSUE THREAD

**Issue by ahkhanjani** [GriffinJohnston/ldrs#22]
Hey there,
Is there any way of using the loaders with server components? Specifically, Next.js app router `loading.tsx` files. The web component structure seems to be making this impossible.
I like the one-for-all frameworks aspect of this library; but we might actually need an RSC compatible version of this; unless I'm missing something.

By the way, thank you for this amazing library.

**Comment by GriffinJohnston** [comment]
For this case, copy/pasting the HTML and CSS is probably the best way to go. I've gotten enough of these questions that I probably will create react components to live alongside the web components at some point. SSR really is a challenge.
