### ISSUE TITLE
Loader doesn't show up with vite production build

### ISSUE THREAD

**Issue by driphireweb** [GriffinJohnston/ldrs#24]
Works on my localhost perfect, but after building with Vite and deploying to cloud it not longer shows up. No errors or anything.

**Comment by GriffinJohnston** [comment]
I'll need a little more info to help. Are you using a Vite preset? React? Some other framework? Do you have a link you can share that shows the issue?

**Comment by Find-Serendipity** [comment]
Hello! I am experiencing the same problem with the Newtons Cradle loader. I'm using it for a final class project.

The loader is on the following site, but loads perfectly fine when I am looking at it on my local host: https://cherry-stone-studios.onrender.com/

Here's some screenshots of the components render tool, which shows that the local is calling the #shadow-root but the live is completely missing it:

![newtonscradle live](https://github.com/GriffinJohnston/ldrs/assets/160557006/256bf719-6309-4e81-bad9-bacd5634be57)
![newtonscradle local](https://github.com/GriffinJohnston/ldrs/assets/160557006/f7e7c1bf-d3ab-4abf-87c2-485864fde171)

I used _npm install vite@latest_ to begin the project, which should reflect in my dependencies, which I will include below. 

Hopefully this is enough information to help!

```
"dependencies": {
    "@prisma/client": "^5.13.0",
    "bcrypt": "^5.1.1",
    "body-parser": "^1.20.2",
    "cors": "^2.8.5",
    "deep-profanity-filter": "^2.3.3",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "faker": "^5.5.3",
    "jest": "^29.7.0",
    "jsonwebtoken": "^9.0.2",
    "ldrs": "^1.0.2",
    "morgan": "^1.10.0",
    "nodemon": "^3.1.0",
    "pg": "^8.11.5",
    "prisma-mock": "^0.10.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-query": "^3.39.3",
    "react-router-dom": "^6.23.1",
    "reactjs-popup": "^2.0.6",
    "redux": "^5.0.1",
    "supertest": "^7.0.0"
```

**Comment by GriffinJohnston** [comment]
Hi @Find-Serendipity, it would be helpful to see some code. How are you adding ldrs to your site?

Here's a simple working example of a Vite + React project using Newton's Cradle: [codesandbox](https://codesandbox.io/p/devbox/zealous-hopper-jxw96l?file=%2Fsrc%2FApp.tsx%3A8%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx2nqjrs00073b6ih5o9m1yw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx2nqjrs00023b6iparbnbj0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx2nqjrs00043b6i4ne67l8t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx2nqjrs00063b6i1wskdfi9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx2nqjrs00023b6iparbnbj0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx2nqjrs00013b6ivy9yxnoz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx2o0m3500023b6iq5tpyj72%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx2nqjrs00023b6iparbnbj0%2522%252C%2522activeTabId%2522%253A%2522clx2o0m3500023b6iq5tpyj72%2522%257D%252C%2522clx2nqjrs00063b6i1wskdfi9%2522%253A%257B%2522id%2522%253A%2522clx2nqjrs00063b6i1wskdfi9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clx2o24d600783b6ivlqiyz58%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx2o24d600783b6ivlqiyz58%2522%257D%252C%2522clx2nqjrs00043b6i4ne67l8t%2522%253A%257B%2522id%2522%253A%2522clx2nqjrs00043b6i4ne67l8t%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx2nz6md00ab3b6i2hkdofhu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clx2nz6ny0085dcip8v971dng%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx2nz6md00ab3b6i2hkdofhu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Find-Serendipity** [comment]
Sure, here's a sample of the button on my login page, where I import the spinner per the directions and then utilize it in a ternary: 

![nc code2](https://github.com/GriffinJohnston/ldrs/assets/160557006/2670f1d2-eb42-4ac2-9139-2f5b6acb0617)
![nc code1](https://github.com/GriffinJohnston/ldrs/assets/160557006/0ddfcb2f-4f6a-4328-b846-34f3c0df7acc)

This loads without problems on the local version, showing me the cradle when the isLoading gets passed through - but as soon as I put this code onto the Render service, the loader vanishes. The isLoading is still being passed through correctly.

**Comment by GriffinJohnston** [comment]
Go ahead and try the manual version if you haven't already:
```js
import { newtonsCradle } from "ldrs"; 
newtonsCradle.register();

**Comment by leunggamciu** [comment]
> Go ahead and try the manual version if you haven't already:
> 
> ```js
> import { newtonsCradle } from "ldrs"; 
> newtonsCradle.register();
> ```

The manual version works for me

**Comment by szulcus** [comment]
I have the same problem. Workaround with manually registration works for me. Thanks!
