### ISSUE TITLE
Sveltekit: Error when evaluating SSR module

### ISSUE THREAD

**Issue by herkyl** [GriffinJohnston/ldrs#26]
I'm getting the error on Sveltekit:
```
8:46:43 PM [vite] Error when evaluating SSR module /src/routes/experiments/[key]/+page.svelte: failed to import "ldrs"
|- ReferenceError: HTMLElement is not defined
```

How do I make ldrs work on Svelte?

**Comment by GriffinJohnston** [comment]
Hi, for SvelteKit I recommend including the CDN version of the loader in a script tag. So in your `app.html`, place the following just after your opening `<body>` tag (changing to the specific loader you want of course):

```
<script
  type="module"
  src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/helix.js"
></script>
```

**Comment by herkyl** [comment]
Can confirm it worked:

Add this to the HTML file:
```html
<script type="module" src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/ripples.js"></script>
```

Then just add this to a Svelte file:
```svelte
<l-ripples
  size="45"
  speed="2"
  color="black" 
></l-ripples>
```
