### ISSUE TITLE
ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by nguyenhai0527** [GriffinJohnston/ldrs#30]
I using with nextjs. That loaded but I have an error

next dev

  ▲ Next.js 14.2.15
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1539ms
 ○ Compiling / ...
 ✓ Compiled / in 2.4s (2755 modules)
 ⨯ **ReferenceError: HTMLElement is not defined**
    

> at __webpack_require__ (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/webpack-runtime.js:33:42)
>     at __webpack_require__ (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/webpack-runtime.js:33:42)
>     at eval (./components/loading/quantum.tsx:9:62)
>     at (ssr)/./components/loading/quantum.tsx (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/app/page.js:173:1)
>     at __webpack_require__ (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/webpack-runtime.js:33:42)
>     at eval (./components/models/trending-prediction.tsx:17:74)
>     at (ssr)/./components/models/trending-prediction.tsx (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/app/page.js:184:1)
>     at __webpack_require__ (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/webpack-runtime.js:33:42)
>     at eval (./components/right-bar-content/contents-page.tsx:11:85)
>     at (ssr)/./components/right-bar-content/contents-page.tsx (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/app/page.js:195:1)
>     at __webpack_require__ (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/webpack-runtime.js:33:42)
>     at eval (./components/home-page.tsx:13:101)
>     at (ssr)/./components/home-page.tsx (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/app/page.js:162:1)
>     at Object.__webpack_require__ [as require] (/Users/<my-user>/Desktop/mse/final/code/<project>/client/.next/server/webpack-runtime.js:33:42)
> digest: "443766814"
>  GET / 500 in 2853ms

 
![image](https://github.com/user-attachments/assets/cca4311d-90d6-45a1-96be-a8c0e7acc54f)
![image](https://github.com/user-attachments/assets/addae892-76ad-4353-9874-c4a299417e24)

**Comment by GriffinJohnston** [comment]
Hi, did you follow the steps in the Nextjs guide? https://github.com/GriffinJohnston/ldrs/blob/main/framework-guides.md#nextjs
