### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by blackrabbit944** [GriffinJohnston/ldrs#4]
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/Users/interface/node_modules/ (uiball/loaders/dist/index.js (1)

**Comment by blackrabbit944** [comment]
find the answer yet. thanks

**Comment by GriffinJohnston** [comment]
> find the answer yet. thanks

I think I need to make the pure ESM part more obvious in the docs. Glad you figured it out!
