### ISSUE TITLE
" Jest encountered an unexpected token..."

### ISSUE THREAD

**Issue by PawaOx4th** [GriffinJohnston/ldrs#6]
I'm facing a problem while working with nextjs and jest for testing application.
<img width="1274" alt="Screen Shot 2565-05-22 at 21 29 29" src="https://user-images.githubusercontent.com/41177171/169700401-0276b100-62a6-4a9f-8e23-6392be182c1d.png">

**Comment by GriffinJohnston** [comment]
This is an issue with Jest and ESM modules - try following the instructions here: https://jestjs.io/docs/ecmascript-modules

**Comment by b3nk3** [comment]
@PawaOx4th did you find a workaround to this?

**Comment by xralphack** [comment]
@b3nk3 I added the following in package.json.
```
"jest": {
    "transformIgnorePatterns": [
      "/node_modules/(?!(?:@uiball\\/loaders)/)"
    ]
  }
  ```
