### ISSUE TITLE
Vue

### ISSUE THREAD

**Issue by reneonguitar** [GriffinJohnston/ldrs#7]
Will there be a Vue version? Thanks.

**Comment by GriffinJohnston** [comment]
This is definitely something I'm interested in doing! I'm currently in the middle of a huge update to another project, but as soon as I have a little breathing room, this could happen. I'll leave this issue open to track.

**Comment by arcbjorn** [comment]
Hey @GriffinJohnston. I'm using your lib on couple of my projects, it's amazing, thank you very much!

If you want, I could take a look at how to implement it in Vue 3.

**Comment by GriffinJohnston** [comment]
@arcbjorn Thanks for the kind words and the offer! I'm actually currently looking into migrating the whole library to https://github.com/BuilderIO/mitosis which would theoretically allow compiling to every major framework, including Vue. So I'd say hold off on that for now. If I take too long, or Mitosis doesn't end up being workable, I'd love for you to spearhead a Vue 3 version though.

**Comment by ilindaniel** [comment]
Any ideas how we could create a React Native lib for this? StyleSheet doesn't support pseudo-elements.

Maybe with [Animated](https://reactnative.dev/docs/animated)?

**Comment by GriffinJohnston** [comment]
@ilindaniel I'm no React Native expert, but I think Animated is likely the way to go. Maybe start a new issue about this?

**Comment by kibotrel** [comment]
I'm bumping this up regarding Vue, would like to use this! Great project overall 🙏

**Comment by GriffinJohnston** [comment]
@kibotrel There's good news on this front actually. I'm 95% finished with a big v2 update that migrates this whole lib over to web components, and adds 12 new loaders to boot. Since the loaders are shipped as custom elements, the new version will be compatible with pretty much everything, including Vue. I'm about to be away from my computer for a week, but the v2 should launch no later than the end of the month.

**Comment by kibotrel** [comment]
That's great news ! Keep up the good work man and take your time 😄

**Comment by GriffinJohnston** [comment]
@kibotrel Officially launched! https://www.producthunt.com/posts/ldrs

**Comment by kibotrel** [comment]
Damn, what a new, i'm excited to try it out. Good job man!
