### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by jgalianoz** [GriffinJohnston/ldrs#8]
I am getting this error when I try to use the library in Remix.

**Error: Error [ERR_REQUIRE_ESM]: require() of ES Module**

**Comment by GriffinJohnston** [comment]
This is an ESM module, so Remix requires an additional step for it to work. See https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages

With the growing popularity of Remix I should definitely add this to the docs. Really they should just support ESM out of the box, but such is life. Leaving this open until the docs are updated.

**Comment by jgalianoz** [comment]
@GriffinJohnston Thx this is working for me.

Here is an example in case anyone else runs into this problem.

`module.exports = {
  serverDependenciesToBundle: ["@uiball/loaders"]
};`
