### ISSUE TITLE
Can suspend be supported?

### ISSUE THREAD

**Issue by WXL570CN** [GriffinJohnston/ldrs#9]
It can not only be used as a loading animation, for example, I used WaveForm in the animation of audio playback, and the animation should also be paused when the audio playback is paused, so I think it would be perfect if your components can support pausing !

**Comment by GriffinJohnston** [comment]
This is actually possible already! If you set `speed` to either `0` or, if you're feeling fun, `Infinity`, the animation will stop playing.

**Comment by GriffinJohnston** [comment]
Reopening to remind myself to add this to the docs.

**Comment by GriffinJohnston** [comment]
Added to docs in 83eaafc15efb26a59119c2fd174ee7d6f846a27d
